#!/bin/bash
#############################################################################
#
# SSH agent forwarding and screen/tmux
#   https://gist.github.com/martijnvermaat/8070533
#   https://gist.github.com/bcomnes/e756624dc1d126ba2eb6
#
#############################################################################

# Fix SSH auth socket location so agent forwarding works with screen.
if [ ! -S "$HOME/.ssh/ssh_auth_sock.$(hostname)" ] && \
    [ -S "$SSH_AUTH_SOCK" ]; then
 ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock.$(hostname)"
fi

# Taken from the sshd(8) manpage.
if read -r proto cookie && [ -n "$DISPLAY" ]; then
  if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:"$(echo "$DISPLAY" |
      cut -c11-)" "$proto" "$cookie"
  else
    # X11UseLocalhost=no
    echo add "$DISPLAY" "$proto" "$cookie"
  fi | xauth -q -
fi

