#!/usr/bin/env zsh

if $BREW_INSTALLED || $BREW_DISABLED; then
  export PATH="$BREW_PREFIX/sbin:$BREW_PREFIX/bin:$PATH"
  export MANPATH="$BREW_PREFIX/share/man:$MANPATH"
  export INFOPATH="$BREW_PREFIX/share/info:$INFOPATH"
  export XDG_DATA_DIRS="$BREW_PREFIX/share:$XDG_DATA_DIRS"

  export BREW_DISABLED=false
fi

return 0
